import os
from dataclasses import dataclass
from typing import Literal

# NB: using os.environ.get inside the dataclass defaults gives a lint error.
HAIL_TMP_DIR = os.environ.get('HAIL_TMP_DIR', '/tmp')  # noqa: S108
HAIL_SEARCH_DATA_DIR = os.environ.get(
    'HAIL_SEARCH_DATA_DIR',
    '/var/seqr/seqr-hail-search-data',
)
LOADING_DATASETS_DIR = os.environ.get(
    'LOADING_DATASETS_DIR',
    '/var/seqr/seqr-loading-temp',
)
PRIVATE_REFERENCE_DATASETS_DIR = os.environ.get(
    'PRIVATE_REFERENCE_DATASETS_DIR',
    '/var/seqr/seqr-reference-data-private',
)
REFERENCE_DATASETS_DIR = os.environ.get(
    'REFERENCE_DATASETS_DIR',
    '/var/seqr/seqr-reference-data',
)
VEP_REFERENCE_DATASETS_DIR = os.environ.get(
    'VEP_REFERENCE_DATASETS_DIR',
    '/var/seqr/vep-reference-data',
)
CLICKHOUSE_DATABASE = os.environ.get('CLICKHOUSE_DATABASE', 'seqr')
CLICKHOUSE_SERVICE_HOSTNAME = os.environ.get(
    'CLICKHOUSE_SERVICE_HOSTNAME',
    'localhost',
)
CLICKHOUSE_SERVICE_PORT = int(os.environ.get('CLICKHOUSE_SERVICE_PORT', '9000'))
CLICKHOUSE_WRITER_PASSWORD = os.environ.get(
    'CLICKHOUSE_WRITER_PASSWORD',
    'default_password',
)
CLICKHOUSE_WRITER_USER = os.environ.get('CLICKHOUSE_WRITER_USER', 'default')
HAIL_BACKEND_SERVICE_HOSTNAME = os.environ.get(
    'HAIL_BACKEND_SERVICE_HOSTNAME',
    'hail-search',
)
HAIL_BACKEND_SERVICE_PORT = int(os.environ.get('HAIL_BACKEND_SERVICE_PORT', '5000'))
CLINGEN_ALLELE_REGISTRY_LOGIN = os.environ.get('CLINGEN_ALLELE_REGISTRY_LOGIN', '')
CLINGEN_ALLELE_REGISTRY_PASSWORD = os.environ.get(
    'CLINGEN_ALLELE_REGISTRY_PASSWORD',
    '',
)
DEPLOYMENT_TYPE = os.environ.get('DEPLOYMENT_TYPE', 'prod')
GCLOUD_DATAPROC_SECONDARY_WORKERS = int(
    os.environ.get('GCLOUD_DATAPROC_SECONDARY_WORKERS', '5'),
)
GCLOUD_PROJECT = os.environ.get('GCLOUD_PROJECT')
GCLOUD_ZONE = os.environ.get('GCLOUD_ZONE')
GCLOUD_REGION = os.environ.get('GCLOUD_REGION')
LOADING_QUEUE_LIMIT = int(os.environ.get('LOADING_QUEUE_LIMIT', '10'))
PIPELINE_RUNNER_APP_VERSION = os.environ.get('PIPELINE_RUNNER_APP_VERSION', 'latest')
SEQR_APP_HAIL_SEARCH_DATA_DIR = os.environ.get('SEQR_APP_HAIL_SEARCH_DATA_DIR')
SEQR_APP_REFERENCE_DATASETS_DIR = os.environ.get('SEQR_APP_REFERENCE_DATASETS_DIR')


@dataclass
class Env:
    CLICKHOUSE_DATABASE: str = CLICKHOUSE_DATABASE
    CLICKHOUSE_SERVICE_HOSTNAME: str = CLICKHOUSE_SERVICE_HOSTNAME
    CLICKHOUSE_SERVICE_PORT: int = CLICKHOUSE_SERVICE_PORT
    CLICKHOUSE_WRITER_PASSWORD: str = CLICKHOUSE_WRITER_PASSWORD
    CLICKHOUSE_WRITER_USER: str = CLICKHOUSE_WRITER_USER
    CLINGEN_ALLELE_REGISTRY_LOGIN: str | None = CLINGEN_ALLELE_REGISTRY_LOGIN
    CLINGEN_ALLELE_REGISTRY_PASSWORD: str | None = CLINGEN_ALLELE_REGISTRY_PASSWORD
    DEPLOYMENT_TYPE: Literal['dev', 'prod'] = DEPLOYMENT_TYPE
    GCLOUD_DATAPROC_SECONDARY_WORKERS: str = GCLOUD_DATAPROC_SECONDARY_WORKERS
    GCLOUD_PROJECT: str | None = GCLOUD_PROJECT
    GCLOUD_ZONE: str | None = GCLOUD_ZONE
    GCLOUD_REGION: str | None = GCLOUD_REGION
    HAIL_BACKEND_SERVICE_HOSTNAME: str | None = HAIL_BACKEND_SERVICE_HOSTNAME
    HAIL_BACKEND_SERVICE_PORT: int = HAIL_BACKEND_SERVICE_PORT
    HAIL_TMP_DIR: str = HAIL_TMP_DIR
    HAIL_SEARCH_DATA_DIR: str = HAIL_SEARCH_DATA_DIR
    LOADING_DATASETS_DIR: str = LOADING_DATASETS_DIR
    LOADING_QUEUE_LIMIT: int = LOADING_QUEUE_LIMIT
    PIPELINE_RUNNER_APP_VERSION: str = PIPELINE_RUNNER_APP_VERSION
    PRIVATE_REFERENCE_DATASETS_DIR: str = PRIVATE_REFERENCE_DATASETS_DIR
    REFERENCE_DATASETS_DIR: str = REFERENCE_DATASETS_DIR
    SEQR_APP_HAIL_SEARCH_DATA_DIR: str | None = SEQR_APP_HAIL_SEARCH_DATA_DIR
    SEQR_APP_REFERENCE_DATASETS_DIR: str | None = SEQR_APP_REFERENCE_DATASETS_DIR
    VEP_REFERENCE_DATASETS_DIR: str = VEP_REFERENCE_DATASETS_DIR
