import os
from dataclasses import dataclass

# Feature Flags
ACCESS_PRIVATE_REFERENCE_DATASETS = (
    os.environ.get('ACCESS_PRIVATE_REFERENCE_DATASETS') == '1'
)
CHECK_SEX_AND_RELATEDNESS = os.environ.get('CHECK_SEX_AND_RELATEDNESS') == '1'
EXPECT_TDR_METRICS = os.environ.get('EXPECT_TDR_METRICS') == '1'
EXPECT_WES_FILTERS = os.environ.get('EXPECT_WES_FILTERS') == '1'
INCLUDE_PIPELINE_VERSION_IN_PREFIX = (
    os.environ.get('INCLUDE_PIPELINE_VERSION_IN_PREFIX') == '1'
)
OVERWRITE_SV_MALE_NON_PAR_CALLS = (
    os.environ.get('OVERWRITE_SV_MALE_NON_PAR_CALLS') == '1'
)
RUN_PIPELINE_ON_DATAPROC = os.environ.get('RUN_PIPELINE_ON_DATAPROC') == '1'
SHOULD_TRIGGER_HAIL_BACKEND_RELOAD = (
    os.environ.get('SHOULD_TRIGGER_HAIL_BACKEND_RELOAD') == '1'
)


@dataclass
class FeatureFlag:
    ACCESS_PRIVATE_REFERENCE_DATASETS: bool = ACCESS_PRIVATE_REFERENCE_DATASETS
    CHECK_SEX_AND_RELATEDNESS: bool = CHECK_SEX_AND_RELATEDNESS
    EXPECT_TDR_METRICS: bool = EXPECT_TDR_METRICS
    EXPECT_WES_FILTERS: bool = EXPECT_WES_FILTERS
    INCLUDE_PIPELINE_VERSION_IN_PREFIX: bool = INCLUDE_PIPELINE_VERSION_IN_PREFIX
    OVERWRITE_SV_MALE_NON_PAR_CALLS: bool = OVERWRITE_SV_MALE_NON_PAR_CALLS
    RUN_PIPELINE_ON_DATAPROC: bool = RUN_PIPELINE_ON_DATAPROC
    SHOULD_TRIGGER_HAIL_BACKEND_RELOAD: bool = SHOULD_TRIGGER_HAIL_BACKEND_RELOAD
