import unittest

import hail as hl

from v03_pipeline.lib.annotations.misc import (
    unmap_formatting_annotation_enums,
    unmap_reference_dataset_annotation_enums,
)
from v03_pipeline.lib.model import (
    DatasetType,
    ReferenceGenome,
)
from v03_pipeline.lib.tasks.exports.misc import camelcase_array_structexpression_fields

TEST_SNV_INDEL_ANNOTATIONS = (
    'v03_pipeline/var/test/exports/GRCh38/SNV_INDEL/annotations.ht'
)


class MiscTest(unittest.TestCase):
    def test_camelcase_array_structexpression_fields(self) -> None:
        ht = hl.read_table(TEST_SNV_INDEL_ANNOTATIONS)
        ht = unmap_formatting_annotation_enums(
            ht,
            ReferenceGenome.GRCh38,
            DatasetType.SNV_INDEL,
        )
        ht = unmap_reference_dataset_annotation_enums(
            ht,
            ReferenceGenome.GRCh38,
            DatasetType.SNV_INDEL,
        )
        ht = camelcase_array_structexpression_fields(ht, ReferenceGenome.GRCh38)
        self.assertEqual(
            ht.collect()[0],
            hl.Struct(
                locus=hl.Locus(
                    contig='chr1',
                    position=939121,
                    reference_genome='GRCh38',
                ),
                alleles=['C', 'T'],
                rg37_locus=hl.Locus(
                    contig=1,
                    position=874501,
                    reference_genome='GRCh37',
                ),
                rsid=None,
                variant_id='1-939121-C-T',
                xpos=1000939121,
                gt_stats=hl.Struct(AC=47, AN=81784, AF=0.0005746845272369683, hom=1),
                CAID='CA502654',
                check_ref=False,
                gnomad_non_coding_constraint=hl.Struct(z_score=None),
                hgmd=None,
                gnomad_exomes=hl.Struct(
                    AF=0.0006690866430290043,
                    AN=1440770,
                    AC=964,
                    Hom=0,
                    AF_POPMAX_OR_GLOBAL=0.0008023773552849889,
                    FAF_AF=0.000633420015219599,
                    Hemi=0,
                ),
                gnomad_genomes=hl.Struct(
                    AF=0.0002759889466688037,
                    AN=152180,
                    AC=42,
                    Hom=0,
                    AF_POPMAX_OR_GLOBAL=0.0005293028079904616,
                    FAF_AF=0.0002092500071739778,
                    Hemi=0,
                ),
                screen=hl.Struct(region_types=[]),
                dbnsfp=hl.Struct(
                    PrimateAI_score=0.5918066501617432,
                    fathmm_MKL_coding_score=0.7174800038337708,
                    CADD_phred=23.5,
                    SIFT_score=0.0010000000474974513,
                    REVEL_score=0.3109999895095825,
                    Polyphen2_HVAR_score=0.164000004529953,
                    VEST4_score=0.39500001072883606,
                    MPC_score=0.01291007362306118,
                    MutPred_score=None,
                    MutationTaster_pred='D',
                ),
                topmed=hl.Struct(
                    AC=41,
                    AF=0.00032651599030941725,
                    AN=125568,
                    Hom=0,
                    Het=41,
                ),
                exac=hl.Struct(
                    AF_POPMAX=0.0007150234305299819,
                    AF=0.00019039999460801482,
                    AC_Adj=20,
                    AC_Het=20,
                    AC_Hom=0,
                    AC_Hemi=None,
                    AN_Adj=47974,
                ),
                splice_ai=hl.Struct(
                    delta_score=0.0,
                    splice_consequence='No consequence',
                ),
                eigen=hl.Struct(Eigen_phred=2.628000020980835),
                clinvar=hl.Struct(
                    alleleId=929885,
                    conflictingPathogenicities=None,
                    goldStars=1,
                    submitters=['Labcorp Genetics (formerly Invitae), Labcorp'],
                    conditions=['not provided'],
                    assertions=[],
                    pathogenicity='Uncertain_significance',
                ),
                sortedTranscriptConsequences=[
                    hl.Struct(
                        aminoAcids='S/L',
                        canonical=1,
                        codons='tCg/tTg',
                        geneId='ENSG00000187634',
                        hgvsc='ENST00000616016.5:c.1049C>T',
                        hgvsp='ENSP00000478421.2:p.Ser350Leu',
                        transcriptId='ENST00000616016',
                        maneSelect='NM_001385641.1',
                        manePlusClinical=None,
                        exon=hl.Struct(index=6, total=14),
                        intron=None,
                        refseqTranscriptId='NM_001385641.1',
                        alphamissense=hl.Struct(pathogenicity=None),
                        loftee=hl.Struct(isLofNagnag=None, lofFilters=None),
                        spliceregion=hl.Struct(
                            extended_intronic_splice_region_variant=False,
                        ),
                        utrannotator=hl.Struct(
                            existingInframeOorfs=None,
                            existingOutofframeOorfs=None,
                            existingUorfs=None,
                            fiveutrAnnotation=None,
                            fiveutrConsequence=None,
                        ),
                        biotype='protein_coding',
                        consequenceTerms=['missense_variant'],
                    ),
                    hl.Struct(
                        aminoAcids='S/L',
                        canonical=None,
                        codons='tCg/tTg',
                        geneId='ENSG00000187634',
                        hgvsc='ENST00000341065.8:c.284C>T',
                        hgvsp='ENSP00000349216.4:p.Ser95Leu',
                        transcriptId='ENST00000341065',
                        maneSelect=None,
                        manePlusClinical=None,
                        exon=hl.Struct(index=4, total=12),
                        intron=None,
                        refseqTranscriptId=None,
                        alphamissense=hl.Struct(pathogenicity=None),
                        loftee=hl.Struct(isLofNagnag=None, lofFilters=None),
                        spliceregion=hl.Struct(
                            extended_intronic_splice_region_variant=False,
                        ),
                        utrannotator=hl.Struct(
                            existingInframeOorfs=None,
                            existingOutofframeOorfs=None,
                            existingUorfs=None,
                            fiveutrAnnotation=None,
                            fiveutrConsequence=None,
                        ),
                        biotype='protein_coding',
                        consequenceTerms=['missense_variant'],
                    ),
                    hl.Struct(
                        aminoAcids='S/L',
                        canonical=None,
                        codons='tCg/tTg',
                        geneId='ENSG00000187634',
                        hgvsc='ENST00000342066.8:c.512C>T',
                        hgvsp='ENSP00000342313.3:p.Ser171Leu',
                        transcriptId='ENST00000342066',
                        maneSelect=None,
                        manePlusClinical=None,
                        exon=hl.Struct(index=6, total=14),
                        intron=None,
                        refseqTranscriptId='NM_152486.4',
                        alphamissense=hl.Struct(pathogenicity=0.1467999964952469),
                        loftee=hl.Struct(isLofNagnag=None, lofFilters=None),
                        spliceregion=hl.Struct(
                            extended_intronic_splice_region_variant=False,
                        ),
                        utrannotator=hl.Struct(
                            existingInframeOorfs=None,
                            existingOutofframeOorfs=None,
                            existingUorfs=None,
                            fiveutrAnnotation=None,
                            fiveutrConsequence=None,
                        ),
                        biotype='protein_coding',
                        consequenceTerms=['missense_variant'],
                    ),
                    hl.Struct(
                        aminoAcids='S/L',
                        canonical=None,
                        codons='tCg/tTg',
                        geneId='ENSG00000187634',
                        hgvsc='ENST00000616125.5:c.512C>T',
                        hgvsp='ENSP00000484643.1:p.Ser171Leu',
                        transcriptId='ENST00000616125',
                        maneSelect=None,
                        manePlusClinical=None,
                        exon=hl.Struct(index=5, total=11),
                        intron=None,
                        refseqTranscriptId=None,
                        alphamissense=hl.Struct(pathogenicity=0.1467999964952469),
                        loftee=hl.Struct(isLofNagnag=None, lofFilters=None),
                        spliceregion=hl.Struct(
                            extended_intronic_splice_region_variant=False,
                        ),
                        utrannotator=hl.Struct(
                            existingInframeOorfs=None,
                            existingOutofframeOorfs=None,
                            existingUorfs=None,
                            fiveutrAnnotation=None,
                            fiveutrConsequence=None,
                        ),
                        biotype='protein_coding',
                        consequenceTerms=['missense_variant'],
                    ),
                    hl.Struct(
                        aminoAcids='S/L',
                        canonical=None,
                        codons='tCg/tTg',
                        geneId='ENSG00000187634',
                        hgvsc='ENST00000617307.5:c.512C>T',
                        hgvsp='ENSP00000482090.2:p.Ser171Leu',
                        transcriptId='ENST00000617307',
                        maneSelect=None,
                        manePlusClinical=None,
                        exon=hl.Struct(index=5, total=13),
                        intron=None,
                        refseqTranscriptId=None,
                        alphamissense=hl.Struct(pathogenicity=0.1467999964952469),
                        loftee=hl.Struct(isLofNagnag=None, lofFilters=None),
                        spliceregion=hl.Struct(
                            extended_intronic_splice_region_variant=False,
                        ),
                        utrannotator=hl.Struct(
                            existingInframeOorfs=None,
                            existingOutofframeOorfs=None,
                            existingUorfs=None,
                            fiveutrAnnotation=None,
                            fiveutrConsequence=None,
                        ),
                        biotype='protein_coding',
                        consequenceTerms=['missense_variant'],
                    ),
                    hl.Struct(
                        aminoAcids='S/L',
                        canonical=None,
                        codons='tCg/tTg',
                        geneId='ENSG00000187634',
                        hgvsc='ENST00000618181.5:c.461C>T',
                        hgvsp='ENSP00000480870.1:p.Ser154Leu',
                        transcriptId='ENST00000618181',
                        maneSelect=None,
                        manePlusClinical=None,
                        exon=hl.Struct(index=4, total=10),
                        intron=None,
                        refseqTranscriptId=None,
                        alphamissense=hl.Struct(pathogenicity=None),
                        loftee=hl.Struct(isLofNagnag=None, lofFilters=None),
                        spliceregion=hl.Struct(
                            extended_intronic_splice_region_variant=False,
                        ),
                        utrannotator=hl.Struct(
                            existingInframeOorfs=None,
                            existingOutofframeOorfs=None,
                            existingUorfs=None,
                            fiveutrAnnotation=None,
                            fiveutrConsequence=None,
                        ),
                        biotype='protein_coding',
                        consequenceTerms=['missense_variant'],
                    ),
                    hl.Struct(
                        aminoAcids='S/L',
                        canonical=None,
                        codons='tCg/tTg',
                        geneId='ENSG00000187634',
                        hgvsc='ENST00000618323.5:c.1049C>T',
                        hgvsp='ENSP00000480678.2:p.Ser350Leu',
                        transcriptId='ENST00000618323',
                        maneSelect=None,
                        manePlusClinical=None,
                        exon=hl.Struct(index=6, total=14),
                        intron=None,
                        refseqTranscriptId='NM_001385640.1',
                        alphamissense=hl.Struct(pathogenicity=None),
                        loftee=hl.Struct(isLofNagnag=None, lofFilters=None),
                        spliceregion=hl.Struct(
                            extended_intronic_splice_region_variant=False,
                        ),
                        utrannotator=hl.Struct(
                            existingInframeOorfs=None,
                            existingOutofframeOorfs=None,
                            existingUorfs=None,
                            fiveutrAnnotation=None,
                            fiveutrConsequence=None,
                        ),
                        biotype='protein_coding',
                        consequenceTerms=['missense_variant'],
                    ),
                    hl.Struct(
                        aminoAcids='S/L',
                        canonical=None,
                        codons='tCg/tTg',
                        geneId='ENSG00000187634',
                        hgvsc='ENST00000618779.5:c.512C>T',
                        hgvsp='ENSP00000484256.1:p.Ser171Leu',
                        transcriptId='ENST00000618779',
                        maneSelect=None,
                        manePlusClinical=None,
                        exon=hl.Struct(index=5, total=12),
                        intron=None,
                        refseqTranscriptId=None,
                        alphamissense=hl.Struct(pathogenicity=0.1467999964952469),
                        loftee=hl.Struct(isLofNagnag=None, lofFilters=None),
                        spliceregion=hl.Struct(
                            extended_intronic_splice_region_variant=False,
                        ),
                        utrannotator=hl.Struct(
                            existingInframeOorfs=None,
                            existingOutofframeOorfs=None,
                            existingUorfs=None,
                            fiveutrAnnotation=None,
                            fiveutrConsequence=None,
                        ),
                        biotype='protein_coding',
                        consequenceTerms=['missense_variant'],
                    ),
                    hl.Struct(
                        aminoAcids='S/L',
                        canonical=None,
                        codons='tCg/tTg',
                        geneId='ENSG00000187634',
                        hgvsc='ENST00000622503.5:c.512C>T',
                        hgvsp='ENSP00000482138.1:p.Ser171Leu',
                        transcriptId='ENST00000622503',
                        maneSelect=None,
                        manePlusClinical=None,
                        exon=hl.Struct(index=5, total=13),
                        intron=None,
                        refseqTranscriptId=None,
                        alphamissense=hl.Struct(pathogenicity=0.1467999964952469),
                        loftee=hl.Struct(isLofNagnag=None, lofFilters=None),
                        spliceregion=hl.Struct(
                            extended_intronic_splice_region_variant=False,
                        ),
                        utrannotator=hl.Struct(
                            existingInframeOorfs=None,
                            existingOutofframeOorfs=None,
                            existingUorfs=None,
                            fiveutrAnnotation=None,
                            fiveutrConsequence=None,
                        ),
                        biotype='protein_coding',
                        consequenceTerms=['missense_variant'],
                    ),
                ],
                sortedRegulatoryFeatureConsequences=[
                    hl.Struct(
                        regulatoryFeatureId='ENSR00000344437',
                        biotype='CTCF_binding_site',
                        consequenceTerms=['regulatory_region_variant'],
                    ),
                ],
                sortedMotifFeatureConsequences=[
                    hl.Struct(
                        motifFeatureId='ENSM00493959715',
                        consequenceTerms=['TF_binding_site_variant'],
                    ),
                ],
            ),
        )
