import os
from dataclasses import dataclass

# Feature Flags
ACCESS_PRIVATE_REFERENCE_DATASETS = (
    os.environ.get('ACCESS_PRIVATE_REFERENCE_DATASETS') == '1'
)
CHECK_SEX_AND_RELATEDNESS = os.environ.get('CHECK_SEX_AND_RELATEDNESS') == '1'
CLICKHOUSE_LOADER_DISABLED = os.environ.get('CLICKHOUSE_LOADER_DISABLED') == '1'
EXPECT_TDR_METRICS = os.environ.get('EXPECT_TDR_METRICS') == '1'
RUN_PIPELINE_ON_DATAPROC = os.environ.get('RUN_PIPELINE_ON_DATAPROC') == '1'


@dataclass
class FeatureFlag:
    ACCESS_PRIVATE_REFERENCE_DATASETS: bool = ACCESS_PRIVATE_REFERENCE_DATASETS
    CHECK_SEX_AND_RELATEDNESS: bool = CHECK_SEX_AND_RELATEDNESS
    CLICKHOUSE_LOADER_DISABLED: bool = CLICKHOUSE_LOADER_DISABLED
    EXPECT_TDR_METRICS: bool = EXPECT_TDR_METRICS
    RUN_PIPELINE_ON_DATAPROC: bool = RUN_PIPELINE_ON_DATAPROC
