#!/usr/bin/env python

import argparse
import json
from urllib2 import urlopen

# based on:
#    https://cwiki.apache.org/confluence/display/solr/Collections+API
#    https://cwiki.apache.org/confluence/display/solr/JSON+Request+API

p = argparse.ArgumentParser() 
p.add_argument("--url", default="69.173.112.35:8983")
p.add_argument("--list", action="store_true")
p.add_argument("--count", metavar="COLLECTON")
p.add_argument("--delete", metavar="COLLECTON")
p.add_argument("--create", metavar="COLLECTON")
p.add_argument("--delete-create", metavar="COLLECTION")
p.add_argument("--num-shards", type=int, default=3)
a = p.parse_args()

url = a.url

def get_json(url):
    print(url)
    return json.loads(urlopen(url).read())

if a.list:
    response_json = get_json("http://%(url)s/solr/admin/collections?action=LIST&wt=json" % locals())
    for c in response_json['collections']:
        print(c)
if a.count:
    collection = a.count
    response_json = get_json("http://%(url)s/solr/%(collection)s/query?q=*:*&rows=0&wt=json" % locals())
    print(response_json['response']['numFound'])
if a.delete:
    collection = a.delete
    response_json = get_json("http://%(url)s/solr/admin/collections?action=DELETE&name=%(collection)s&wt=json" % locals())
    print(response_json)
if a.create:
    collection = a.create
    num_shards = a.num_shards
    response_json = get_json("http://%(url)s/solr/admin/collections?action=CREATE&name=%(collection)s&numShards=%(num_shards)s&wt=json" % locals())
    print(response_json)
if a.delete_create:
    collection = a.delete_create
    num_shards = a.num_shards
    response_json = get_json("http://%(url)s/solr/admin/collections?action=DELETE&name=%(collection)s&wt=json" % locals())
    print(response_json)
    response_json = get_json("http://%(url)s/solr/admin/collections?action=CREATE&name=%(collection)s&numShards=%(num_shards)s&wt=json" % locals())
    print(response_json)


